# 기본적으로 활성화할 프로파일 설정
spring:
  profiles:
    active: local
  application:
    name: springboot-trace-scan
  database:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.web: WARN
    io.micrometer.prometheus: WARN

---

# local 프로파일 설정
spring:
  application:
    name: local-springboot-trace-scan
  config:
    activate:
      on-profile: local

logging:
  file:
    name: logs/app.log
    path: logs


---

# develop 프로파일 설정
spring:
  application:
    name: dev-springboot-trace-scan
  config:
    activate:
      on-profile: develop

logging:
  file:
    name: /app/logs/app.log
    path: /app/logs

